[package]
name = "viuer"
version = "0.1.0"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
description = "Display images in the terminal"
documentation = "https://docs.rs/viuer"
readme = "README.md"
repository = "https://github.com/atanunq/viuer"
license = "MIT"
categories = ["command-line-interface"]
keywords = ["terminal", "image"]

[dependencies]
termcolor = "1.1"
crossterm = "0.18"
ansi_colours = "1.0"
image = "0.23"
base64 = "0.13"
tempfile = "3.1"
console = "0.13"
lazy_static = "1.4"
