[package]
name = "viuer"
version = "0.6.2"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2021"
description = "Display images in the terminal"
documentation = "https://docs.rs/viuer"
readme = "README.md"
repository = "https://github.com/atanunq/viuer"
license = "MIT"
categories = ["command-line-interface"]
keywords = ["terminal", "image"]
exclude = [".github"]

[dependencies]
termcolor = "1.1"
crossterm = "0.25"
ansi_colours = "1.0"
image = "0.24"
base64 = "0.13"
tempfile = "3.1"
console = { version = "0.15", default-features = false }
lazy_static = "1.4"

[dependencies.sixel-rs]
version = "0.3.3"
optional = true

[features]
default = []
sixel = ["sixel-rs"]
