[package]
name = "viuer"
version = "0.4.0"
authors = ["Atanas Yankov <atanas.yankov98@gmail.com>"]
edition = "2018"
description = "Display images in the terminal"
documentation = "https://docs.rs/viuer"
readme = "README.md"
repository = "https://github.com/atanunq/viuer"
license = "MIT"
categories = ["command-line-interface"]
keywords = ["terminal", "image"]
exclude = [".github"]

[dependencies]
termcolor = "1.1"
crossterm = "0.19"
ansi_colours = "1.0"
image = "0.23"
base64 = "0.13"
tempfile = "3.1"
console = { version = "0.14", default-features = false }
lazy_static = "1.4"
sixel-sys = { version = "0.3.1", optional = true }

# avoid feature and crate name collision (thanks rabite0/hunter)
[dependencies.sixel-rs]
package = "sixel"
version = "0.3.2"
optional = true

[features]
default = []
sixel = ["sixel-rs", "sixel-sys"]
